/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppManagementIndexRouteImport } from './routes/app/management/index'
import { Route as AppUserIndexRouteImport } from './routes/app/_user/index'
import { Route as AppComponentsBottomBarAdminRouteImport } from './routes/app/_components/bottom-bar-admin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppManagementIndexRoute = AppManagementIndexRouteImport.update({
  id: '/app/management/',
  path: '/app/management/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUserIndexRoute = AppUserIndexRouteImport.update({
  id: '/app/_user/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppComponentsBottomBarAdminRoute =
  AppComponentsBottomBarAdminRouteImport.update({
    id: '/app/_components/bottom-bar-admin',
    path: '/app/bottom-bar-admin',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/bottom-bar-admin': typeof AppComponentsBottomBarAdminRoute
  '/app': typeof AppUserIndexRoute
  '/app/management': typeof AppManagementIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/bottom-bar-admin': typeof AppComponentsBottomBarAdminRoute
  '/app': typeof AppUserIndexRoute
  '/app/management': typeof AppManagementIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/_components/bottom-bar-admin': typeof AppComponentsBottomBarAdminRoute
  '/app/_user/': typeof AppUserIndexRoute
  '/app/management/': typeof AppManagementIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app/bottom-bar-admin' | '/app' | '/app/management'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app/bottom-bar-admin' | '/app' | '/app/management'
  id:
    | '__root__'
    | '/'
    | '/app/_components/bottom-bar-admin'
    | '/app/_user/'
    | '/app/management/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppComponentsBottomBarAdminRoute: typeof AppComponentsBottomBarAdminRoute
  AppUserIndexRoute: typeof AppUserIndexRoute
  AppManagementIndexRoute: typeof AppManagementIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/management/': {
      id: '/app/management/'
      path: '/app/management'
      fullPath: '/app/management'
      preLoaderRoute: typeof AppManagementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_user/': {
      id: '/app/_user/'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppUserIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_components/bottom-bar-admin': {
      id: '/app/_components/bottom-bar-admin'
      path: '/app/bottom-bar-admin'
      fullPath: '/app/bottom-bar-admin'
      preLoaderRoute: typeof AppComponentsBottomBarAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppComponentsBottomBarAdminRoute: AppComponentsBottomBarAdminRoute,
  AppUserIndexRoute: AppUserIndexRoute,
  AppManagementIndexRoute: AppManagementIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
